/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateCategoryBody,
  DeleteCategory200,
  GetCategoryById200,
  ListCategories200Item,
  UpdateCategory200,
  UpdateCategoryBody,
} from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const listCategories = (options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<ListCategories200Item[]>({ url: `/api/categories/`, method: "GET" }, options)
}
export const createCategory = (
  createCategoryBody: CreateCategoryBody,
  options?: SecondParameter<typeof requestSafe>,
) => {
  return requestSafe<void>(
    {
      url: `/api/categories/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCategoryBody,
    },
    options,
  )
}
export const getCategoryById = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<GetCategoryById200>({ url: `/api/categories/${id}`, method: "GET" }, options)
}
export const updateCategory = (
  id: number,
  updateCategoryBody: UpdateCategoryBody,
  options?: SecondParameter<typeof requestSafe>,
) => {
  return requestSafe<UpdateCategory200>(
    {
      url: `/api/categories/${id}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateCategoryBody,
    },
    options,
  )
}
export const deleteCategory = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<DeleteCategory200>({ url: `/api/categories/${id}`, method: "DELETE" }, options)
}
export type ListCategoriesResult = NonNullable<Awaited<ReturnType<typeof listCategories>>>
export type CreateCategoryResult = NonNullable<Awaited<ReturnType<typeof createCategory>>>
export type GetCategoryByIdResult = NonNullable<Awaited<ReturnType<typeof getCategoryById>>>
export type UpdateCategoryResult = NonNullable<Awaited<ReturnType<typeof updateCategory>>>
export type DeleteCategoryResult = NonNullable<Awaited<ReturnType<typeof deleteCategory>>>
