/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCommentBody, UpdateCommentBody } from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getCommentById = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>({ url: `/api/comments/${id}`, method: "GET" }, options)
}
export const updateComment = (
  id: number,
  updateCommentBody: UpdateCommentBody,
  options?: SecondParameter<typeof requestSafe>,
) => {
  return requestSafe<void>(
    {
      url: `/api/comments/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCommentBody,
    },
    options,
  )
}
export const deleteComment = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>({ url: `/api/comments/${id}`, method: "DELETE" }, options)
}
export const createComment = (createCommentBody: CreateCommentBody, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>(
    { url: `/api/comments/`, method: "POST", headers: { "Content-Type": "application/json" }, data: createCommentBody },
    options,
  )
}
export type GetCommentByIdResult = NonNullable<Awaited<ReturnType<typeof getCommentById>>>
export type UpdateCommentResult = NonNullable<Awaited<ReturnType<typeof updateComment>>>
export type DeleteCommentResult = NonNullable<Awaited<ReturnType<typeof deleteComment>>>
export type CreateCommentResult = NonNullable<Awaited<ReturnType<typeof createComment>>>
