/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCourse201, CreateCourseBody, ListCourses200Item } from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const createCourse = (createCourseBody: CreateCourseBody, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<CreateCourse201>(
    { url: `/api/courses/`, method: "POST", headers: { "Content-Type": "application/json" }, data: createCourseBody },
    options,
  )
}
export const listCourses = (options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<ListCourses200Item[]>({ url: `/api/courses/`, method: "GET" }, options)
}
export const getCourseById = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>({ url: `/api/courses/${id}`, method: "GET" }, options)
}
export const updateCourse = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>({ url: `/api/courses/${id}`, method: "PATCH" }, options)
}
export const deleteCourse = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>({ url: `/api/courses/${id}`, method: "DELETE" }, options)
}
export type CreateCourseResult = NonNullable<Awaited<ReturnType<typeof createCourse>>>
export type ListCoursesResult = NonNullable<Awaited<ReturnType<typeof listCourses>>>
export type GetCourseByIdResult = NonNullable<Awaited<ReturnType<typeof getCourseById>>>
export type UpdateCourseResult = NonNullable<Awaited<ReturnType<typeof updateCourse>>>
export type DeleteCourseResult = NonNullable<Awaited<ReturnType<typeof deleteCourse>>>
