/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getFileById = (id: string, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>({ url: `/files/${id}`, method: "GET" }, options)
}
export type GetFileByIdResult = NonNullable<Awaited<ReturnType<typeof getFileById>>>
