/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { Health200 } from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const health = (options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<Health200>({ url: `/api/health`, method: "GET" }, options)
}
export type HealthResult = NonNullable<Awaited<ReturnType<typeof health>>>
