/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type { RequestPasswordResetBody, ResetPasswordBody } from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const requestPasswordReset = (
  requestPasswordResetBody: RequestPasswordResetBody,
  options?: SecondParameter<typeof requestSafe>,
) => {
  return requestSafe<void>(
    {
      url: `/api/password-reset/request`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: requestPasswordResetBody,
    },
    options,
  )
}
export const resetPassword = (resetPasswordBody: ResetPasswordBody, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<void>(
    {
      url: `/api/password-reset/reset`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: resetPasswordBody,
    },
    options,
  )
}
export type RequestPasswordResetResult = NonNullable<Awaited<ReturnType<typeof requestPasswordReset>>>
export type ResetPasswordResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
