/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateThread200,
  CreateThreadBody,
  DeleteThread200,
  GetThreadById200,
  ListThreads200,
  ListThreadsParams,
  UpdateThread200,
  UpdateThreadBody,
} from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const listThreads = (params: ListThreadsParams, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<ListThreads200>({ url: `/threads/`, method: "GET", params }, options)
}
export const createThread = (createThreadBody: CreateThreadBody, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<CreateThread200>(
    { url: `/threads/`, method: "POST", headers: { "Content-Type": "application/json" }, data: createThreadBody },
    options,
  )
}
export const getThreadById = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<GetThreadById200>({ url: `/threads/${id}`, method: "GET" }, options)
}
export const updateThread = (
  id: number,
  updateThreadBody: UpdateThreadBody,
  options?: SecondParameter<typeof requestSafe>,
) => {
  return requestSafe<UpdateThread200>(
    { url: `/threads/${id}`, method: "PATCH", headers: { "Content-Type": "application/json" }, data: updateThreadBody },
    options,
  )
}
export const deleteThread = (id: number, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<DeleteThread200>({ url: `/threads/${id}`, method: "DELETE" }, options)
}
export type ListThreadsResult = NonNullable<Awaited<ReturnType<typeof listThreads>>>
export type CreateThreadResult = NonNullable<Awaited<ReturnType<typeof createThread>>>
export type GetThreadByIdResult = NonNullable<Awaited<ReturnType<typeof getThreadById>>>
export type UpdateThreadResult = NonNullable<Awaited<ReturnType<typeof updateThread>>>
export type DeleteThreadResult = NonNullable<Awaited<ReturnType<typeof deleteThread>>>
