/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateUser201,
  CreateUserBody,
  DeleteProfileImage200,
  GetUserProfile200,
  UpdateUserProfile200,
  UpdateUserProfileBody,
  UploadProfileImage200,
} from "./generated.schemas"

import { requestSafe } from "../../utils/axios"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new user
 */
export const createUser = (createUserBody: CreateUserBody, options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<CreateUser201>(
    { url: `/api/users/`, method: "POST", headers: { "Content-Type": "application/json" }, data: createUserBody },
    options,
  )
}
/**
 * Get user profile
 */
export const getUserProfile = (options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<GetUserProfile200>({ url: `/api/users/me`, method: "GET" }, options)
}
/**
 * Update user profile
 */
export const updateUserProfile = (
  updateUserProfileBody: UpdateUserProfileBody,
  options?: SecondParameter<typeof requestSafe>,
) => {
  return requestSafe<UpdateUserProfile200>(
    {
      url: `/api/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateUserProfileBody,
    },
    options,
  )
}
/**
 * Upload a profile image
 */
export const uploadProfileImage = (options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<UploadProfileImage200>({ url: `/api/users/profile-image`, method: "PUT" }, options)
}
/**
 * Delete a profile image
 */
export const deleteProfileImage = (options?: SecondParameter<typeof requestSafe>) => {
  return requestSafe<DeleteProfileImage200>({ url: `/api/users/profile-image`, method: "DELETE" }, options)
}
export type CreateUserResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
export type GetUserProfileResult = NonNullable<Awaited<ReturnType<typeof getUserProfile>>>
export type UpdateUserProfileResult = NonNullable<Awaited<ReturnType<typeof updateUserProfile>>>
export type UploadProfileImageResult = NonNullable<Awaited<ReturnType<typeof uploadProfileImage>>>
export type DeleteProfileImageResult = NonNullable<Awaited<ReturnType<typeof deleteProfileImage>>>
