/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
export type Health200Status = (typeof Health200Status)[keyof typeof Health200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Health200Status = {
  ok: "ok",
} as const

export type Health200 = {
  status: Health200Status
  time: string
  uptime: number
}

export type LoginBody = {
  email: string
  password: string
}

export type Login200Message = (typeof Login200Message)[keyof typeof Login200Message]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Login200Message = {
  Authenticated_successfully: "Authenticated successfully",
} as const

export type Login200 = {
  message: Login200Message
}

export type Login401 = {
  message: string
}

export type GetApiLoginGoogleCallback200Message =
  (typeof GetApiLoginGoogleCallback200Message)[keyof typeof GetApiLoginGoogleCallback200Message]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiLoginGoogleCallback200Message = {
  Authenticated_successfully: "Authenticated successfully",
} as const

export type GetApiLoginGoogleCallback200 = {
  message: GetApiLoginGoogleCallback200Message
}

export type GetApiLoginGoogleCallback401 = {
  message: string
}

export type CreateUserBody = {
  email: string
  name: string
  /** @nullable */
  picture?: string | null
  /** @minLength 6 */
  password: string
}

/**
 * @nullable
 */
export type CreateUser201 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  picture?: string | null
} | null

/**
 * @nullable
 */
export type UploadProfileImage200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  picture?: string | null
} | null

export type UploadProfileImage400 = {
  message: string
}

export type UploadProfileImage500 = {
  message: string
}

export type DeleteProfileImage200 = {
  message: string
}

export type DeleteProfileImage404 = {
  message: string
}

/**
 * @nullable
 */
export type GetUserProfile200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  picture?: string | null
} | null

export type UpdateUserProfileBody = {
  name?: string
  email?: string
  /** @nullable */
  picture?: string | null
  currentPassword?: string
  /** @minLength 6 */
  newPassword?: string
  /** @minLength 6 */
  confirmPassword?: string
}

/**
 * @nullable
 */
export type UpdateUserProfile200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  picture?: string | null
} | null
