/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
export type PostApiAuthLoginBody = {
  email: string
  password: string
}

export type PostApiAuthLogin200 = {
  token: string
}

export type PostApiAuthLogin401 = {
  message: string
}

export type CreateUserBody = {
  email: string
  name: string
  /** @minLength 6 */
  password: string
}

/**
 * @nullable
 */
export type GetUserProfile200 = {
  id: number
  email: string
  name: string
  createdAt: string
  updatedAt: string
} | null

export type UpdateUserProfileBody = {
  name?: string
  email?: string
  /** @minLength 6 */
  password?: string
}

/**
 * @nullable
 */
export type UpdateUserProfile200 = {
  id: number
  email: string
  name: string
  createdAt: string
  updatedAt: string
} | null
