/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API documentation
 * OpenAPI spec version: 1.0.0
 */
export type Health200Status = (typeof Health200Status)[keyof typeof Health200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Health200Status = {
  ok: "ok",
} as const

export type Health200 = {
  status: Health200Status
  time: string
  uptime: number
}

export type LoginBody = {
  email: string
  password: string
}

export type Login200 = {
  token: string
}

export type Login401 = {
  message: string
}

export type GetApiLoginGoogleCallback401 = {
  message: string
}

export type ListCategories200Item = {
  id: number
  name: string
}

export type CreateCategoryBody = {
  name: string
}

export type GetCategoryById200 = {
  id: number
  name: string
}

export type GetCategoryById404 = {
  message: string
}

export type UpdateCategoryBody = {
  name: string
}

export type UpdateCategory200 = {
  id: number
  name: string
}

export type UpdateCategory404 = {
  message: string
}

export type DeleteCategory200 = {
  success: boolean
}

export type DeleteCategory404 = {
  message: string
}

export type UpdateCommentBody = {
  /** @minLength 1 */
  content: string
}

export type CountLikes200 = {
  count: number
}

export type RequestPasswordResetBody = {
  email: string
}

export type ResetPasswordBody = {
  token: string
  /** @minLength 8 */
  password: string
}

export type RecordPostView200Type = (typeof RecordPostView200Type)[keyof typeof RecordPostView200Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecordPostView200Type = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

/**
 * @nullable
 */
export type RecordPostView200EventDate = string | string | null

export type RecordPostView200CreatedAt = string | string

export type RecordPostView200UpdatedAt = string | string

export type RecordPostView200Author = {
  id: number
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId: string | null
}

export type RecordPostView200CoursesItem = {
  id: number
  name: string
  code: string
}

export type _RecordPostView200Count = {
  likes?: number
}

export type RecordPostView200 = {
  id: number
  title: string
  content: string
  type: RecordPostView200Type
  isPinned: boolean
  /** @nullable */
  eventDate: RecordPostView200EventDate
  /** @nullable */
  location: string | null
  views: number
  createdAt: RecordPostView200CreatedAt
  updatedAt: RecordPostView200UpdatedAt
  author: RecordPostView200Author
  courses: RecordPostView200CoursesItem[]
  isLiked?: boolean
  _count: _RecordPostView200Count
}

export type ListPostsParams = {
  page: number
  take: number
  search?: string
  course?: number
  type?: ListPostsType
}

export type ListPostsType = (typeof ListPostsType)[keyof typeof ListPostsType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListPostsType = {
  EVENT: "EVENT",
  NEWS: "NEWS",
} as const

export type ListPosts200DataItemType = (typeof ListPosts200DataItemType)[keyof typeof ListPosts200DataItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListPosts200DataItemType = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

/**
 * @nullable
 */
export type ListPosts200DataItemEventDate = string | string | null

export type ListPosts200DataItemCreatedAt = string | string

export type ListPosts200DataItemUpdatedAt = string | string

export type ListPosts200DataItemAuthor = {
  id: number
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId: string | null
}

export type ListPosts200DataItemCoursesItem = {
  id: number
  name: string
  code: string
}

export type _ListPosts200DataItemCount = {
  likes?: number
}

export type ListPosts200DataItem = {
  id: number
  title: string
  content: string
  type: ListPosts200DataItemType
  isPinned: boolean
  /** @nullable */
  eventDate: ListPosts200DataItemEventDate
  /** @nullable */
  location: string | null
  views: number
  createdAt: ListPosts200DataItemCreatedAt
  updatedAt: ListPosts200DataItemUpdatedAt
  author: ListPosts200DataItemAuthor
  courses: ListPosts200DataItemCoursesItem[]
  isLiked?: boolean
  _count: _ListPosts200DataItemCount
}

export type ListPosts200 = {
  data: ListPosts200DataItem[]
  total: number
  page: number
  perPage: number
  totalPages: number
}

export type CreatePostBodyType = (typeof CreatePostBodyType)[keyof typeof CreatePostBodyType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePostBodyType = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

export type CreatePostBody = {
  /** @minLength 1 */
  title: string
  /** @minLength 1 */
  content: string
  type: CreatePostBodyType
  isPinned?: boolean
  eventDate?: string
  location?: string
  courses?: number[]
}

export type CreatePost201Type = (typeof CreatePost201Type)[keyof typeof CreatePost201Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePost201Type = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

/**
 * @nullable
 */
export type CreatePost201EventDate = string | string | null

export type CreatePost201CreatedAt = string | string

export type CreatePost201UpdatedAt = string | string

export type CreatePost201Author = {
  id: number
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId: string | null
}

export type CreatePost201CoursesItem = {
  id: number
  name: string
  code: string
}

export type _CreatePost201Count = {
  likes?: number
}

export type CreatePost201 = {
  id: number
  title: string
  content: string
  type: CreatePost201Type
  isPinned: boolean
  /** @nullable */
  eventDate: CreatePost201EventDate
  /** @nullable */
  location: string | null
  views: number
  createdAt: CreatePost201CreatedAt
  updatedAt: CreatePost201UpdatedAt
  author: CreatePost201Author
  courses: CreatePost201CoursesItem[]
  isLiked?: boolean
  _count: _CreatePost201Count
}

export type GetPostById200Type = (typeof GetPostById200Type)[keyof typeof GetPostById200Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPostById200Type = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

/**
 * @nullable
 */
export type GetPostById200EventDate = string | string | null

export type GetPostById200CreatedAt = string | string

export type GetPostById200UpdatedAt = string | string

export type GetPostById200Author = {
  id: number
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId: string | null
}

export type GetPostById200CoursesItem = {
  id: number
  name: string
  code: string
}

export type _GetPostById200Count = {
  likes?: number
}

export type GetPostById200 = {
  id: number
  title: string
  content: string
  type: GetPostById200Type
  isPinned: boolean
  /** @nullable */
  eventDate: GetPostById200EventDate
  /** @nullable */
  location: string | null
  views: number
  createdAt: GetPostById200CreatedAt
  updatedAt: GetPostById200UpdatedAt
  author: GetPostById200Author
  courses: GetPostById200CoursesItem[]
  isLiked?: boolean
  _count: _GetPostById200Count
}

export type UpdatePostBodyType = (typeof UpdatePostBodyType)[keyof typeof UpdatePostBodyType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePostBodyType = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

export type UpdatePostBody = {
  /** @minLength 1 */
  title?: string
  /** @minLength 1 */
  content?: string
  type?: UpdatePostBodyType
  isPinned?: boolean
  eventDate?: string
  location?: string
  courses?: number[]
}

export type UpdatePost200Type = (typeof UpdatePost200Type)[keyof typeof UpdatePost200Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePost200Type = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

/**
 * @nullable
 */
export type UpdatePost200EventDate = string | string | null

export type UpdatePost200CreatedAt = string | string

export type UpdatePost200UpdatedAt = string | string

export type UpdatePost200Author = {
  id: number
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId: string | null
}

export type UpdatePost200CoursesItem = {
  id: number
  name: string
  code: string
}

export type _UpdatePost200Count = {
  likes?: number
}

export type UpdatePost200 = {
  id: number
  title: string
  content: string
  type: UpdatePost200Type
  isPinned: boolean
  /** @nullable */
  eventDate: UpdatePost200EventDate
  /** @nullable */
  location: string | null
  views: number
  createdAt: UpdatePost200CreatedAt
  updatedAt: UpdatePost200UpdatedAt
  author: UpdatePost200Author
  courses: UpdatePost200CoursesItem[]
  isLiked?: boolean
  _count: _UpdatePost200Count
}

export type DeletePost200Type = (typeof DeletePost200Type)[keyof typeof DeletePost200Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePost200Type = {
  NEWS: "NEWS",
  EVENT: "EVENT",
} as const

/**
 * @nullable
 */
export type DeletePost200EventDate = string | string | null

export type DeletePost200CreatedAt = string | string

export type DeletePost200UpdatedAt = string | string

export type DeletePost200Author = {
  id: number
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId: string | null
}

export type DeletePost200CoursesItem = {
  id: number
  name: string
  code: string
}

export type _DeletePost200Count = {
  likes?: number
}

export type DeletePost200 = {
  id: number
  title: string
  content: string
  type: DeletePost200Type
  isPinned: boolean
  /** @nullable */
  eventDate: DeletePost200EventDate
  /** @nullable */
  location: string | null
  views: number
  createdAt: DeletePost200CreatedAt
  updatedAt: DeletePost200UpdatedAt
  author: DeletePost200Author
  courses: DeletePost200CoursesItem[]
  isLiked?: boolean
  _count: _DeletePost200Count
}

export type ListThreadsParams = {
  page: number
  take: number
  search?: string
  categoryId?: number
}

export type ListThreads200DataItemCreatedAt = string | string

export type ListThreads200DataItemUpdatedAt = string | string

export type ListThreads200DataItemAuthor = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type ListThreads200DataItemCommentsItemCreatedAt = string | string

export type ListThreads200DataItemCommentsItemAuthor = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type ListThreads200DataItemCommentsItem = {
  id: number
  content: string
  createdAt: ListThreads200DataItemCommentsItemCreatedAt
  author: ListThreads200DataItemCommentsItemAuthor
}

export type ListThreads200DataItemCategoriesItem = {
  id: number
  name: string
}

export type ListThreads200DataItem = {
  id: number
  title: string
  content: string
  createdAt: ListThreads200DataItemCreatedAt
  updatedAt: ListThreads200DataItemUpdatedAt
  author: ListThreads200DataItemAuthor
  comments: ListThreads200DataItemCommentsItem[]
  categories: ListThreads200DataItemCategoriesItem[]
}

export type ListThreads200 = {
  data: ListThreads200DataItem[]
  total: number
  page: number
  perPage: number
  totalPages: number
}

export type CreateThreadBody = {
  /** @minLength 2 */
  title: string
  /** @minLength 2 */
  content: string
  categories?: number[]
}

export type CreateThread200CreatedAt = string | string

export type CreateThread200UpdatedAt = string | string

export type CreateThread200Author = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type CreateThread200CommentsItemCreatedAt = string | string

export type CreateThread200CommentsItemAuthor = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type CreateThread200CommentsItem = {
  id: number
  content: string
  createdAt: CreateThread200CommentsItemCreatedAt
  author: CreateThread200CommentsItemAuthor
}

export type CreateThread200CategoriesItem = {
  id: number
  name: string
}

export type CreateThread200 = {
  id: number
  title: string
  content: string
  createdAt: CreateThread200CreatedAt
  updatedAt: CreateThread200UpdatedAt
  author: CreateThread200Author
  comments: CreateThread200CommentsItem[]
  categories: CreateThread200CategoriesItem[]
}

export type GetThreadById200CreatedAt = string | string

export type GetThreadById200UpdatedAt = string | string

export type GetThreadById200Author = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type GetThreadById200CommentsItemCreatedAt = string | string

export type GetThreadById200CommentsItemAuthor = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type GetThreadById200CommentsItem = {
  id: number
  content: string
  createdAt: GetThreadById200CommentsItemCreatedAt
  author: GetThreadById200CommentsItemAuthor
}

export type GetThreadById200CategoriesItem = {
  id: number
  name: string
}

export type GetThreadById200 = {
  id: number
  title: string
  content: string
  createdAt: GetThreadById200CreatedAt
  updatedAt: GetThreadById200UpdatedAt
  author: GetThreadById200Author
  comments: GetThreadById200CommentsItem[]
  categories: GetThreadById200CategoriesItem[]
}

export type UpdateThreadBody = {
  title?: string
  content?: string
  categories?: number[]
}

export type UpdateThread200CreatedAt = string | string

export type UpdateThread200UpdatedAt = string | string

export type UpdateThread200Author = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type UpdateThread200CommentsItemCreatedAt = string | string

export type UpdateThread200CommentsItemAuthor = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type UpdateThread200CommentsItem = {
  id: number
  content: string
  createdAt: UpdateThread200CommentsItemCreatedAt
  author: UpdateThread200CommentsItemAuthor
}

export type UpdateThread200CategoriesItem = {
  id: number
  name: string
}

export type UpdateThread200 = {
  id: number
  title: string
  content: string
  createdAt: UpdateThread200CreatedAt
  updatedAt: UpdateThread200UpdatedAt
  author: UpdateThread200Author
  comments: UpdateThread200CommentsItem[]
  categories: UpdateThread200CategoriesItem[]
}

export type DeleteThread200CreatedAt = string | string

export type DeleteThread200UpdatedAt = string | string

export type DeleteThread200Author = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type DeleteThread200CommentsItemCreatedAt = string | string

export type DeleteThread200CommentsItemAuthor = {
  id: number
  name: string
  /** @nullable */
  profilePicId: string | null
}

export type DeleteThread200CommentsItem = {
  id: number
  content: string
  createdAt: DeleteThread200CommentsItemCreatedAt
  author: DeleteThread200CommentsItemAuthor
}

export type DeleteThread200CategoriesItem = {
  id: number
  name: string
}

export type DeleteThread200 = {
  id: number
  title: string
  content: string
  createdAt: DeleteThread200CreatedAt
  updatedAt: DeleteThread200UpdatedAt
  author: DeleteThread200Author
  comments: DeleteThread200CommentsItem[]
  categories: DeleteThread200CategoriesItem[]
}

export type CreateUserBody = {
  email: string
  name: string
  /** @nullable */
  profilePicId?: string | null
  /** @minLength 8 */
  password: string
}

/**
 * @nullable
 */
export type CreateUser201 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId?: string | null
} | null

export type Refresh200 = {
  token: string
}

export type Refresh401 = {
  message: string
}

export type CreateCommentBody = {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  threadId: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  authorId: number
  /** @minLength 1 */
  content: string
}

export type LikePost201 = {
  id: number
  userId: number
  postId: number
}

export type UnlikePost200 = {
  success: boolean
}

/**
 * @nullable
 */
export type GetUserProfile200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId?: string | null
} | null

export type UpdateUserProfileBodyRole = (typeof UpdateUserProfileBodyRole)[keyof typeof UpdateUserProfileBodyRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserProfileBodyRole = {
  USER: "USER",
} as const

export type UpdateUserProfileBody = {
  /** @maxLength 255 */
  name?: string
  email?: string
  /** @nullable */
  profilePicId?: string | null
  /** @minLength 8 */
  currentPassword?: string
  /** @minLength 8 */
  newPassword?: string
  /** @minLength 8 */
  confirmPassword?: string
  role?: UpdateUserProfileBodyRole
}

/**
 * @nullable
 */
export type UpdateUserProfile200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId?: string | null
} | null

/**
 * @nullable
 */
export type UploadProfileImage200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId?: string | null
} | null

export type UploadProfileImage400 = {
  message: string
}

export type UploadProfileImage500 = {
  message: string
}

/**
 * @nullable
 */
export type DeleteProfileImage200 = {
  id: number
  email: string
  /** @nullable */
  name: string | null
  /** @nullable */
  profilePicId?: string | null
} | null

export type DeleteProfileImage404 = {
  message: string
}

export type CreateCourseBody = {
  name: string
  code: string
  description: string
}

export type CreateCourse201 = {
  id: number
  code: string
}

export type ListCourses200Item = {
  id: number
  code: string
}
