name: Docker Image Build

env:
  DOCKER_REGISTRY: docker.kauan.sh

on:
  push:
    branches: [ "main" ]

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push API
      uses: docker/build-push-action@v6
      with:
        context: api
        file: api/Dockerfile
        push: true
        build-args: |
          DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432?schema=public
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URI=${{ secrets.GOOGLE_CALLBACK_URI }}
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
        tags: |
            ${{ env.DOCKER_REGISTRY }}/faculhub-api:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/faculhub-api:latest

  build_front:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push frontend
      uses: docker/build-push-action@v6
      with:
        context: front
        file: front/Dockerfile
        push: true
        build-args: |
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
        tags: |
            ${{ env.DOCKER_REGISTRY }}/faculhub-front:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/faculhub-front:latest

